# docker compose version
version: '3.9'

# container declare inside service
services:
  server:
    build: .
    ports:
      - ${PORT}:${PORT} # local port:container port
    volumes:
      - .:/app
    depends_on:
      - database
  database:
    image: mysql
    restart: always
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - .dbdata:/var/lib/mysql
