# docker compose version
version: '3.9'

# container declare inside service
services:
  server:
    build: .
    ports:
      - 3000:3000 # local port:container port
    volumes:
      - .:/app
    depends_on:
      - mongodb
  mongodb:
    image: mongo
    container_name: 'algo-project-mongodb'
    restart: always
    ports:
      - '${MONGODB_PORT}:${MONGODB_PORT}'
    environment:
      MONGO_INITDB_ROOT_DATABASE: ${DATABASE_NAME}
      MONGO_INITDB_ROOT_USERNAME: ${DATABASE_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - .dbdata:/val/lib/mongodb
